[project]
name = "pytoexe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "nuitka>=2.7.11",
    "pyinstaller>=6.14.2",
    "tkinterdnd2>=0.4.3",
    "ttkbootstrap>=1.14.0",
]
